---
- name: Test of 1Password Role
  hosts: localhost
  vars:
    test: "{{ lookup('onepassword', 'ops-gitea-1', section='db', field='username', vault='homelab', domain=op_domain, secret_key=op_key, master_password=op_password) }}"

  tasks:
    - debug:
        var: test