- name: Setup 1Password CLI for AWX
  hosts: localhost
  tasks:
    - name: Install 1Password Binary
      unarchive:
        src: "https://cache.agilebits.com/dist/1P/op/pkg/v{{ op_version }}/op_linux_amd64_v{{ op_version }}.zip"
        dest: /usr/local/bin
        remote_src: yes
        exclude: op.sig
