- name: Setup 1Password CLI for AWX
  hosts: all
  tasks:
    - name: Install 1Password Binary
      unarchive:
        src: "https://cache.agilebits.com/dist/1P/op/pkg/v{{ op_version }}/op_linux_amd64_v{{ op_version }}.zip"
        dest: /usr/local/bin
        remote_src: yes
        exclude: op.sig
    - name: Update onepassword.py
      get_url:
        url: https://raw.githubusercontent.com/ansible/ansible/v2.8.0rc2/lib/ansible/plugins/lookup/onepassword.py
        dest: /usr/lib/python2.7/site-packages/ansible/plugins/lookup/onepassword.py
        force: yes


